"""Добавление таблицы пользователей

Revision ID: 0461fdf155b3
Revises: 
Create Date: 2021-04-03 21:51:21.497143

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0461fdf155b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sv_users',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False, comment='Уникальный идентификатор пользователя'),
    sa.Column('email', mysql.VARCHAR(length=32), nullable=False, comment='Эл почта пользователя и логин'),
    sa.Column('password', mysql.VARCHAR(length=64), nullable=False, comment='Пароль пользователя'),
    sa.Column('fullname', mysql.VARCHAR(length=64), nullable=True, comment='ФИО пользователя'),
    sa.Column('phone', mysql.VARCHAR(length=16), nullable=True, comment='Номер телефона'),
    sa.Column('user_desc', mysql.VARCHAR(length=512), nullable=True, comment='Краткое описание'),
    sa.Column('disabled', sa.CHAR(length=1), nullable=True, comment='Признак блокировки аккаунта'),
    sa.Column('verified', sa.CHAR(length=1), nullable=True, comment='Признак верификации аккаунта'),
    sa.Column('create_date', mysql.TIMESTAMP(), nullable=False, comment='Дата создания аккаунта'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sv_users')
    # ### end Alembic commands ###
