"""Добавление таблиц

Revision ID: 7b15e46f8a95
Revises: 0461fdf155b3
Create Date: 2021-04-03 22:13:19.256040

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7b15e46f8a95'
down_revision = '0461fdf155b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sv_sites',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False, comment='Уникальный идентификатор ресурса'),
    sa.Column('uid', mysql.INTEGER(display_width=11), nullable=False, comment='Уникальный идентификатор владельца сайта'),
    sa.Column('site_desc', mysql.VARCHAR(length=512), nullable=True, comment='Краткое описание'),
    sa.Column('short_link', mysql.VARCHAR(length=64), nullable=True, comment='Короткая ссылка'),
    sa.Column('img_link', mysql.VARCHAR(length=64), nullable=True, comment='Ссылка на снимок экрана сайта'),
    sa.Column('fast_rait', mysql.INTEGER(display_width=11), nullable=True, comment='Рейтинг сайта'),
    sa.Column('create_date', mysql.TIMESTAMP(), nullable=False, comment='Дата создания аккаунта'),
    sa.Column('disabled', sa.CHAR(length=1), nullable=True, comment='Признак блокировки'),
    sa.Column('verified', sa.CHAR(length=1), nullable=True, comment='Признак верификации'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sv_votes',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False, comment='Уникальный идентификатор'),
    sa.Column('sid', mysql.INTEGER(display_width=11), nullable=False, comment='Уникальный идентификатор ресурса'),
    sa.Column('vote_type', mysql.INTEGER(display_width=11), nullable=False, comment='Тип голоса из словаря'),
    sa.Column('email', mysql.VARCHAR(length=32), nullable=False, comment='Эл почта голосующего'),
    sa.Column('phone', mysql.VARCHAR(length=16), nullable=True, comment='Номер телефона голосующего'),
    sa.Column('vote_date', mysql.TIMESTAMP(), nullable=False, comment='Дата голосоания'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sv_config',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False, comment='Уникальный идентификатор'),
    sa.Column('key', mysql.VARCHAR(length=32), nullable=False, comment='Ключ поля'),
    sa.Column('value', mysql.VARCHAR(length=16), nullable=True, comment='Значение поля'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sv_vote_type',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False, comment='Уникальный идентификатор'),
    sa.Column('value', mysql.VARCHAR(length=16), nullable=True, comment='Значение поля'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sv_vote_type')
    op.drop_table('sv_config')
    op.drop_table('sv_votes')
    op.drop_table('sv_sites')
    # ### end Alembic commands ###
